# Generated by Django 5.1 on 2024-08-19 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFile',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progressive', models.IntegerField(choices=[(0, '240p'), (1, '360p'), (2, '480p'), (3, '720p'), (4, '1080p')], default=1)),
                ('movie_id', models.BigIntegerField(db_index=True, null=True, verbose_name='Movie ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
